apiVersion: v1
    kind: Service
    metadata:
        name: jaeger-query
        labels:
            app: jaeger
            jaeger-infra: jaeger-service
    spec:
        ports:
            - name: query-http
              port: 80
              protocol: TCP
              targetPort: 16686
        selector:
            jaeger-infra: jaeger-pod
        type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: jaeger-ui-ingress
    annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/auth-type: "basic"
        traefik.ingress.kubernetes.io/auth-secret: {{ .Values.ui.secret | quote }}
spec:
    rules:
        - host: {{ .Values.ui.url }}
          http:
              paths:
                  - path: /
                    backend:
                        serviceName: jaeger-query
                        servicePort: query-http